base_url = "https://127.0.0.1"
title = "Arnaldo Garcia"
description = ""
default_language = "en"

build_search_index = true
generate_feeds = true
minify_html = false

taxonomies = [
  { name = "tags", feed = true },
  { name = "categories" },
]

[extra.footer]
include_cc_license = true

[extra.navbar]
items = [
  { url = "/", name = "Home" },
  { url = "/blog", name = "Blog" },
  { url = "/categories", name = "Categories" },
  { url = "/tags", name = "Tags" },
  { url = "/tags", name = "Contact" },
]
title = "Arnaldo Garcia"

# Index page
[extra.index]
title = "Arnaldo Garcia"
messages = [
  { text = "This blog documents my work with Linux, containers,", duration = "2s", steps = 49, delay = "0s"},
  { text = "and experiments with various technologies.", duration = "1.8s", steps = 40, delay = "2s" },
  { text = "All opinions expressed are my own.", duration = "1.5s", steps = 30, delay = "3.8s" , bold = true }
]

[extra.contact]
codeberg = ""
github = "https://github.com/arnaldo2792"
